"use client";
import { useState } from "react";
const presets={writing:"Write a clear, engaging article",coding:"Build a reliable software solution",study:"Teach this topic step by step",creative:"Create an original creative concept"};
export default function AIWorkspace({slug}:{slug:string}){
 const [input,setInput]=useState(""); const [type,setType]=useState<keyof typeof presets>("writing"); const [out,setOut]=useState("");
 const library=["Writing: Rewrite this text for clarity and keep the meaning.","Coding: Explain the bug, propose a fix, then show a minimal example.","Study: Explain the topic simply, then quiz me with 5 questions.","Creative: Generate 5 distinct ideas with pros and cons."];
 const run=()=>{const base=input.trim(); if(slug==="ai-prompt-library"){setOut(library.join("\n\n"));return} if(!base){setOut("Enter your idea first.");return} if(slug==="ai-prompt-builder") setOut(`Role: Expert ${type} assistant\nTask: ${presets[type]}: ${base}\nRequirements: Be accurate, structured, concise, and state assumptions.\nOutput: Give the result in clear sections and useful examples.`); else setOut(`Improve this prompt while preserving the user's goal:\n\n${base}\n\nMake it specific, add context, constraints, desired format, and success criteria. Do not change the intended task.`);};
 return <div className="workspace"><label>Idea or prompt<textarea rows={7} value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe what you want AI to do..." /></label>{slug==="ai-prompt-builder"&&<label>Use case<select value={type} onChange={e=>setType(e.target.value)}>{Object.keys(presets).map(k=><option key={k}>{k}</option>)}</select></label>}<button className="primary-button" onClick={run}>{slug==="ai-prompt-library"?"Show prompt library":slug==="ai-prompt-builder"?"Build prompt":"Improve prompt"}</button>{out&&<div className="result-card"><pre className="overflow-auto whitespace-pre-wrap">{out}</pre><button onClick={()=>navigator.clipboard?.writeText(out)}>Copy</button></div>}</div>;
}
