"use client";
import { useState } from "react";

type Mode = "document" | "passport" | "labels";
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");

export default function PrinterWorkspace(){
 const [mode,setMode]=useState<Mode>("document");
 const [text,setText]=useState("");
 const [size,setSize]=useState("A4");
 const [orientation,setOrientation]=useState("portrait");
 const [photo,setPhoto]=useState<string>("");
 const [label,setLabel]=useState("PRODUCT NAME\nMRP: ₹____");
 const [cols,setCols]=useState(3),[rows,setRows]=useState(8),[lw,setLw]=useState(60),[lh,setLh]=useState(30);
 const printDocument=()=>{const w=window.open("","_blank","width=900,height=700");if(!w)return;const body=esc(text).replace(/\n/g,"<br>");w.document.write(`<!doctype html><html><head><title>QuickToolMaster Print</title><style>@page{size:${size} ${orientation};margin:18mm}body{font-family:Arial,sans-serif;font-size:14pt;line-height:1.5;white-space:normal}@media print{body{color:#000}}</style></head><body>${body}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
 const printPassport=()=>{if(!photo)return;const w=window.open("","_blank","width=900,height=700");if(!w)return;const photos=Array.from({length:20},()=>`<img src="${photo}" />`).join("");w.document.write(`<!doctype html><html><head><title>Passport Size Photos</title><style>@page{size:A4 portrait;margin:10mm}body{margin:0}.sheet{display:grid;grid-template-columns:repeat(4,35mm);grid-auto-rows:45mm;gap:4mm 4mm;align-items:start}.sheet img{width:35mm;height:45mm;object-fit:cover;display:block}</style></head><body><div class="sheet">${photos}</div></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)};
 const printLabels=()=>{const w=window.open("","_blank","width=900,height=700");if(!w)return;const items=Array.from({length:Math.max(1,cols*rows)},()=>`<div class="label">${esc(label).replace(/\n/g,"<br>")}</div>`).join("");w.document.write(`<!doctype html><html><head><title>Commercial Labels</title><style>@page{size:A4 portrait;margin:10mm}body{margin:0;font-family:Arial,sans-serif}.sheet{display:grid;grid-template-columns:repeat(${cols},${lw}mm);grid-auto-rows:${lh}mm;gap:3mm;align-items:stretch}.label{width:${lw}mm;height:${lh}mm;box-sizing:border-box;border:0.25mm solid #777;padding:3mm;font-size:11pt;line-height:1.35;display:flex;align-items:center;justify-content:center;text-align:center;overflow:hidden;white-space:normal}</style></head><body><div class="sheet">${items}</div></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)};
 return <div className="workspace">
  <div className="control-grid"><label>Print type<select value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="document">Document / Text</option><option value="passport">Passport Size Photo</option><option value="labels">Commercial Labels</option></select></label></div>
  {mode==="document"&&<><label>Text to print<textarea rows={12} value={text} onChange={e=>setText(e.target.value)} placeholder="Type or paste your document here…" /></label><div className="control-grid"><label>Paper size<select value={size} onChange={e=>setSize(e.target.value)}><option>A4</option><option>A5</option><option>Letter</option></select></label><label>Orientation<select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label></div><button className="primary-button" disabled={!text.trim()} onClick={printDocument}>🖨️ Print / Save as PDF</button></>}
  {mode==="passport"&&<><label>Choose photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f)}}}/></label>{photo&&<div style={{margin:"12px 0"}}><img src={photo} alt="Passport preview" style={{width:120,height:154,objectFit:"cover",borderRadius:8}}/><p className="text-sm">Prints 20 passport-size photos per A4 sheet, each 35 × 45 mm.</p></div>}<button className="primary-button" disabled={!photo} onClick={printPassport}>🖨️ Print Passport Photos</button></>}
  {mode==="labels"&&<><label>Label text<textarea rows={4} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Product name, MRP, SKU, address…" /></label><div className="control-grid"><label>Columns<input type="number" min="1" max="6" value={cols} onChange={e=>setCols(Math.min(6,Math.max(1,+e.target.value||1)))}/></label><label>Rows<input type="number" min="1" max="20" value={rows} onChange={e=>setRows(Math.min(20,Math.max(1,+e.target.value||1)))}/></label><label>Width (mm)<input type="number" min="20" max="100" value={lw} onChange={e=>setLw(Math.min(100,Math.max(20,+e.target.value||20)))}/></label><label>Height (mm)<input type="number" min="15" max="70" value={lh} onChange={e=>setLh(Math.min(70,Math.max(15,+e.target.value||15)))}/></label></div><p className="text-sm">Creates a bordered A4 label sheet for product/commercial printing. Default: 24 labels (3 × 8).</p><button className="primary-button" disabled={!label.trim()} onClick={printLabels}>🖨️ Print Commercial Labels</button></>}
  <p className="text-sm">The browser print dialog lets you select a physical printer or <b>Save as PDF</b>.</p>
 </div>;
}
